### ISSUE TITLE
Change the file extension

### ISSUE THREAD

**Issue by yocontra** [gulp-community/gulp-pug#1]
file.shortened and file.path both need to have their file extensions modified from .jade to .js before passing it along to a .folder()

**Comment by yocontra** [comment]
Use replaceExtension from https://github.com/wearefractal/gulp-util

**Comment by yocontra** [comment]
@funkytek has an example at https://github.com/wearefractal/gulp-coffee/blob/master/index.js#L14

**Comment by phated** [comment]
Looks easy enough. Will do it when I wake up.

**Comment by yocontra** [comment]
You probably want to do .html for non-client ones too

**Comment by yocontra** [comment]
:+1:

**Comment by OnkelTem** [comment]
I use [gulp-rename](https://www.npmjs.com/package/gulp-rename) for setting destination extensions.

Example:

``` js
var gulp = require('gulp');
var jade = require('gulp-jade-php');
var rename = require('gulp-rename');
var yaml = require('js-yaml');
var fs = require('fs');
var data = require('gulp-data');
var path = require('path');
var config = require('../config').jade;

gulp.task('jade', function() {
  return gulp
    .src(config.src)
    .pipe(data(function(file) {
      var datafile = config.data + '/' + path.basename(file.path, '.jade') + '.yaml';
      return fs.exists(datafile) ? yaml.safeLoad(fs.readFileSync(datafile, 'utf8')) : null;
    }))
    .pipe(jade({pretty: true, debug: false}))
    .on('error', function () { console.log(arguments); })
    .pipe(rename({
        extname: ".tpl.php"
    }))
    .pipe(gulp.dest(config.dest));
});
```

**Comment by koofah** [comment]
is it possible to compile jade to pure text or different extensions other than html? I know this sounds kind of silly but is it possible and how?

**Comment by phated** [comment]
There are other plugins that change extensions for you. Plugins should do 1 thing.
