### ISSUE TITLE
Dependencies error on install.

### ISSUE THREAD

**Issue by diazemiliano-zz** [gulp-community/gulp-pug#103]
Hi i'm trying to install `gulp-jade v1.1.0` with `node v0.10.36` and `npm v3.3.6` and i've the following erros and I can't compile jade files.

``` bash
npm WARN install Couldnt install optional dependency: Unsupported
nahuelhuapi-theme-dev@0.0.1 /home/ediaz/wordpress-4.2.3-0/apps/wordpress/htdocs/wp-content/themes/nahuelhuapi
├── gulp-jade@1.1.0 
└── jade@1.11.0 

npm WARN EPACKAGEJSON nahuelhuapi-theme-dev@0.0.1 No repository field.
npm WARN EPACKAGEJSON nahuelhuapi-theme-dev@0.0.1 license should be a valid SPDX license expression
```

**Comment by phated** [comment]
This looks to have installed gulp-jade but you have warnings that are related to your package.json and some dependency named "Unsupported" which is super weird.   Anyway, this is a problem with your environment/npm, not gulp-jade
