### ISSUE TITLE
gulp-jade with gulp-data not throwing errors

### ISSUE THREAD

**Issue by marcobarbosa** [gulp-community/gulp-pug#105]
Hi,

I'm having issues where the gulp-data plugin is not giving me compilation errors. 

Please see my compile-jade task below.

```
'use strict';

var path = require('path');

module.exports = function(gulp, plugins, config, browserSync) {
    return function() {
        var jadeParams = {
            pretty: true,
            compileDebug: true
        };
        gulp.src(config.templatesSource, { base: './src' })
            .pipe(plugins.data(function(file) {
                try {
                    return require( path.resolve( '.', config.dataFile ) );
                } catch (e) {
                    return plugins.util.log(plugins.util.colors.magenta('jade error'), e);
                }
            }))
            .pipe(plugins.jade(jadeParams))
            .pipe(gulp.dest(config.outputDistDir))
            .pipe(browserSync.stream());
    };
};
```

If I run `gulp compile-jade` I simply get the "task finished" in the terminal. Running `jade <template>` manually in the terminal gives me the syntax error that I want.

If I remove the `plugins.data` pipe part, then running `gulp compile-jade` again will give me the correct syntax errors. So I'm wondering, what is wrong with the require above? Why is it making jade not give me errors?

Everything will work fine without any syntax error (including the data being passed). 

Can you spot any errors with this approach?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow

**Comment by marcobarbosa** [comment]
http://stackoverflow.com/questions/33274613/gulp-jade-with-gulp-data-not-throwing-errors
