### ISSUE TITLE
jade is now pug

### ISSUE THREAD

**Issue by coverslide** [gulp-community/gulp-pug#110]
Just putting this here since this will need to be transitioned to pug soon.

https://github.com/pugjs/jade/issues/2184

**Comment by artem-malko** [comment]
@phated is there any news?)

**Comment by coverslide** [comment]
Looks like the update is to use this: https://www.npmjs.com/package/gulp-pug Closing this, and @phated should post a deprecation notice.

**Comment by phated** [comment]
That's not the solution and this isn't deprecated.
