### ISSUE TITLE
Catch errors without stopping gulp.watch ?

### ISSUE THREAD

**Issue by houkanshan** [gulp-community/gulp-pug#12]
I'm building my project with `gulp.watch`, but it seems that gulp watch would quit when `jade()` failed.

And I failed trying to use `jade().on('error', gutil.log)` to catch error while `gulp.watch` .

Then I fixed it with a `try...catch...` block: 

``` javascript
    if(file.isBuffer()){
      try {
        file.contents = new Buffer(handleCompile(String(file.contents), opts));
      } catch(e) {
        this.emit('error', new Error(e))
      }
    }
```

Or is there any way to solve this ? Thx.

**Comment by phated** [comment]
Due to jade compilation being synchronous, I will probably have to add that try/catch in this module.  Thanks for catching that.

If you want to submit a PR, I will accept it asap.

**Comment by baio** [comment]
Hi, I have a problem with handling such error, code bellow from gulp file, but it is invoked only after first exception, an watcher seems to stop reacting on changes of the file (though gulp doesn't exit from task)

```
.pipe(jade().on('error', function(err) {
      console.log(err);
})
...
```

**Comment by phated** [comment]
Fixed in `0.4.1` which was just published to npm.

**Comment by Jamesgt** [comment]
Looks like this happens again. gulp 3.8.10, gulp-jade 0.9.0

**Comment by alexrqs** [comment]
@Jamesgt `true` but is fixed in `"gulp-jade": "^0.10.0",`

**Comment by Jamesgt** [comment]
Sorry that I'm repeating myself, but looks like this happens again.
gulp 3.9.0, gulp-jade 1.1.0

**Comment by phated** [comment]
Put an error handler on your stream...
