### ISSUE TITLE
Don't assume folder structure by compiling pug to html

### ISSUE THREAD

**Issue by marvinhuebner** [gulp-community/gulp-pug#124]
Is there any way to not assume the folder structure of my jade files by compiling it?

For example my pug template structure looks like this:

```
Navigation-Components (Folder)
|-- Main-nav (Folder)
|   -- main-nav.jade
|-- Sub-nav (Folder)
|   -- sub-nav.jade
|-- Footer-nav (Folder)
|    -- footer-nav.jade
```

and then the output look like this:

```
Navigation-Components (Folder)
|-- Main-nav (Folder)
|   -- main-nav.html
|-- Sub-nav (Folder)
|   -- sub-nav.html
|-- Footer-nav (Folder)
|    -- footer-nav.html
```

Is there an option to become this as my output:

```
Navigation-Components (Folder)
|-- main-nav.html
|-- sub-nav.html
|-- footer-nav.html
```

This is only a example, my jade templates are much more complex and i need to pair several files in difference folders.

My gulp task looks like this:

``` js
gulp.task('jade', function () {
    gulp.src('html/components/**/*.jade')
        .pipe(jade({
            pretty: true
        }))

        .pipe(gulp.dest('public/docs'));
});
```

Big thanks in advance for help!

**Comment by jamen** [comment]
Hello, thanks for reaching out.

`gulp-pug` itself doesn't concatenate files any further than imports.

What you could do is setup your gulp task so it compiles each of the folders and outputs the HTML individually...  Here is something that might work, although I can't test at the moment...  But just to give you the idea:

``` javascript
var compile = pug(...);
gulp.src('components/main-nav/main-nav.pug', { base: 'components/main-nav' })
.pipe(compile)
.pipe(gulp.dest('out'))

gulp.src('components/footer-nav/footer-nav.pug', { base: 'components/footer-nav' })
.pipe(compile);
.pipe(gulp.dest('out'));

// ...
```

If you wanted, you could write yourself a function to make the code more pretty:

``` javascript
function compile(base, file) {
  return gulp.src(base + '/' + file, { base: base })
  .pipe(pug({ ...opts }))
  .pipe(gulp.dest('out'));
};

compile('components/footer-nav', 'footer-nav.pug');
compile('components/sub-nav', 'sub-nav.pug');
// ...
```

Again, this is untested so I don't know 100% that it works, but maybe it gives you the idea.

**Comment by marvinhuebner** [comment]
I have done already something similar

``` js
gulp.task('jade', jadeTask);

function jadeTask() {
    var compileJade = function (basePath, destPath) {
        gulp.src(sourcePath + 'html/' + basePath + '/*.jade')
            .pipe(jade({
                pretty: true
            }))
            .pipe(gulp.dest(destPath));
    };

    compileJade('main', 'public');
    compileJade('sub', 'public');
}
```

This will do the job. I hoped that there is a more dynamic way to do this. If i do it like that, i have to adjust it every time when i add a component folder. But probably there is no other way.

**Comment by jamen** [comment]
There might be a Gulp plugin somewhere that can help you with something like that, but I'm unaware of any.  I think organization like that is outside the scope of this package. Consider making a plugin if there isn't one. :)

**Comment by marvinhuebner** [comment]
I will look for something. Thanks for your help! :)

**Comment by marvinhuebner** [comment]
**I found a solution.** 

_Maybe some others are searching for something like that, i still want to post it. It is a little bit dirty but it works._

``` js
var gulp = require('gulp');
var jade = require('gulp-jade');
var gulpCopy = require('gulp-copy');
var del = require('del');

// copy files to another directory
gulp.task('copy', function(){
    return gulp.src('html/docs/**/*.jade')
        .pipe(gulpCopy('html/compile', {prefix: 3}));
});

// async jade task which waits till copy task is ready and then it compiles the files from the copied directory
gulp.task('jade', ['copy'], function (){
    return gulp.src('html/compile/*jade')
        .pipe(jade({
            pretty: true
        }))
        .pipe(gulp.dest('public'));
});

// delete task waits till jade task is ready, when it removes the copied files, because you don't need the files two times in the git
gulp.task('delete', ['jade'], function () {
    return del([
        'html/compile/*.jade'
    ]);
});

// merge all tasks in one command
gulp.task('docs', [
    'copy',
    'jade',
    'delete'
]);
```
