### ISSUE TITLE
Mention `externalRuntime` more explicitly as an option for `compileClient` because without it does not compile to a single function

### ISSUE THREAD

**Issue by niftylettuce** [gulp-community/gulp-pug#127]

**Comment by niftylettuce** [comment]
I think it is actually `inlineRuntimeFunctions` instead of `externalRuntime`

**Comment by jamen** [comment]
I'll look into it.  But I didn't see any documentation on this type of stuff.  Is it v2?

Edit: Never mind, looks like it is documented in `pug-code-gen`

**Comment by phated** [comment]
It looks like this is now the default for `compileClient` according to the pug docs.
