### ISSUE TITLE
Any way to catch errors without stopping gulp?

### ISSUE THREAD

**Issue by davidxcarroll** [gulp-community/gulp-pug#133]
My current pug and watch:

```
// PUG

var pug = require('gulp-pug');

gulp.task('pug', function() {
  gulp.src('./src/**/*.pug')
  .pipe(pug({
    pretty: true
  }))
  .pipe(pug().on('error', pug.logError))
  .pipe(gulp.dest('./public'))
});

// WATCH

gulp.task('watch', function() {
  gulp.watch(['./src/**/*.pug'], ['pug']),
  gulp.watch(['./src/sass/**/*.scss'],['sass']);
});
```

I'm assuming this line could be improved? And/or relocated?
`.pipe(pug().on('error', pug.logError))`

Thanks in advance! And sorry, I tried doing research before posting but couldn't find something I could implement. I'm pretty new to Gulp and Pug.

**Comment by jamen** [comment]
I think it's a pretty universal problem in Gulp plugins.  A plugin called [`gulp-plumber`](https://www.npmjs.com/package/gulp-plumber) helps with the situation.  Let me know if it solves your problem.

**Comment by davidxcarroll** [comment]
Will do, thanks!

**Comment by jamen** [comment]
Assuming your issue was solved?  Closing this.  :+1:

**Comment by davidxcarroll** [comment]
Yes @jamen thank you :)
