### ISSUE TITLE
RangeError in plugin 'gulp-pug'

### ISSUE THREAD

**Issue by edwardessing** [gulp-community/gulp-pug#137]
Hey, currently getting this error:

`Plumber found unhandled error:
 RangeError in plugin 'gulp-pug'
Message:
    Maximum call stack size exceeded
Details:
    undefined: true`

Here are my current dependencies:
`
  "devDependencies": {
    "browser-sync": "^2.14.0",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-changed": "^1.3.1",
    "gulp-concat": "^2.6.0",
    "gulp-jshint": "^2.0.1",
    "gulp-plumber": "^1.1.0",
    "gulp-pug": "^3.0.3",
    "gulp-sass": "^2.3.2",
    "gulp-uglify": "^1.5.4",
    "jshint": "^2.9.2"
  }
`

**Comment by jamen** [comment]
Can you try using `gulp-pug@3.0.4`?  Looks like you are using `3.0.3`.

**Comment by edwardessing** [comment]
Still getting it...

**Comment by jamen** [comment]
Hmm, well this error seems very vague.  Can you show me the piece of code where you are using `gulp-pug`?

**Comment by edwardessing** [comment]
Here is how it appears in my gulpfile

`gulp.task('pug', function() {`
    `gulp.src('src/pug/**/*.pug')`
        `.pipe(plumber())`
        `.pipe(pug())`
        `.pipe(gulp.dest(buildPath))`
        `.pipe(sync.reload({ stream: true }));`
`});`

**Comment by edwardessing** [comment]
So as it turns out I was trying to include a block within itself...block-ception.

For what it's worth, gulp-jade was able to pick up on this dumb mistake...

**Comment by jamen** [comment]
Glad you could solve your issue.

Also, this package is gulp-jade.  It was transitioned from jade to pug, but the functionality was left the same.  Any differences between gulp-jade and gulp-pug is something to do with changes in pug or new feature additions in v2 (which wouldn't have existed in gulp-jade).
