### ISSUE TITLE
Adding filters

### ISSUE THREAD

**Issue by roelvangils** [gulp-community/gulp-pug#138]
Do I need another Gulp plugin (such as `gulp-filters`) to use custom filters? I'm not sure where to define or include a filter. The documentation has no information on this, I believe.

Do I have to pass filter names as an option when using `.pipe(pug(…))`?

I was hoping it would work as explained in the documentation for the (deprecated)  `gulp-jade` plugin:

```
pug.filters.markdown = function (str) {
  return str.toMarkdown();
}
```

This doesn't seem to work for `gulp-pug`. Specifically, I want to use a Markdown filer in my Pug templates, so I can use this syntax:

```
body
  main
    :markdown
      # Welcome
      Hello **world**!
```

Thanks for your help.

**Comment by roelvangils** [comment]
Solved it. It turned out to be as easy as including `jstransformer` and the right filter in my `gulpfile.js`.

```
var transformer = require('jstransformer');
var markdown = transformer(require('jstransformer-marked'));
```

**Comment by jamen** [comment]
See how it is done here in the test case: https://github.com/jamen/gulp-pug/blob/master/test/filters.js

I agree with you that it should be documented better.  I'll leave this open until I can get around to that.

**Comment by jamen** [comment]
This is actually documented [here](https://pugjs.org/language/filters.html) now.
