### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by nickdriller** [gulp-community/gulp-pug#140]
I'm working with Bootstrap-JADE [http://rajasegar.github.io/JADE-Bootstrap/getting-started.html](url) i changed the extension to .pug and using gulp-pug for compiling.
For example i've got this mixin

``` jade
mixin icon(name)
    span(class='glyphicon glyphicon-#{name}', aria-hidden='true')
```

this is how i'm using it

``` jade
+icon('test')
```

and this is how compiles

``` html
<span class="glyphicon glyphicon-#{name}" aria-hidden="true"></span>
```

When i change the file extensions to .jade and use gulp-jade compiles correctly. Also works in Codepen 

``` html
<span aria-hidden="true" class="glyphicon glyphicon-test"></span>
```

I'm thinking this is a gulp-pug issue

**Comment by jamen** [comment]
Hello.  This is [a breaking change with `pug`](https://github.com/pugjs/pug/issues/2305).  You'd want to update to something like this:

``` js
mixin icon(name)
    span(class='glyphicon glyphicon-'+name, aria-hidden='true')
```
