### ISSUE TITLE
Migrating to the pugjs org

### ISSUE THREAD

**Issue by ForbesLindesay** [gulp-community/gulp-pug#144]
Would you be interested in moving this repo into the pugjs org?  Still with you maintaining it, but it might give this more visibility as the "official" gulp pug implementation.

**Comment by jamen** [comment]
Sure! I attempted to transfer, but it said I do not have permission for the pugjs organization.

Do you want to add me or should I transfer it to you, or what?

**Comment by ForbesLindesay** [comment]
Oops, you should now have a pending invitation to join the pugjs team.  Once you've accepted that you should be able to transfer the repo.

**Comment by jamen** [comment]
@ForbesLindesay I have moved the package. :)

Not as far as links and stuff go though.
