### ISSUE TITLE
Jinja2 Template lang + gulp-pug

### ISSUE THREAD

**Issue by yeralin** [gulp-community/gulp-pug#148]
Hi,
I've been trying to compile pugjs with Jinja2, but it throws errors: unexpected text "{% lo"

I know that I can simply put "| {%", but I found it inconvenient. Is there any option so I could suppress these warnings?

Also, I tried to use this fork https://github.com/matannoam/pypugjs but it seems a little buggy (also I think that at some point it will slow down django)

**Comment by jamen** [comment]
Please see [Plain Text](https://pugjs.org/language/plain-text.html) in pugjs docs.

It looks like you want the `.` syntax here if I understand correctly.
