### ISSUE TITLE
compiling Jade files

### ISSUE THREAD

**Issue by tolson32** [gulp-community/gulp-pug#150]
I'm using jade for the first time. I installed Node.js and I'm using notepadd ++ to write in jade. 
I used the command prompt to install jade with:

C:\Users\tom>npm install jade
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
C:\Users\tom
`-- jade@1.11.0
  +-- character-parser@1.2.1
  +-- clean-css@3.4.20
  | +-- commander@2.8.1
  | | `-- graceful-readlink@1.0.1
  | `-- source-map@0.4.4
  |   `-- amdefine@1.0.1
  +-- commander@2.6.0
  +-- constantinople@3.0.2
  | `-- acorn@2.7.0
  +-- jstransformer@0.0.2
  | +-- is-promise@2.1.0
  | `-- promise@6.1.0
  |   `-- asap@1.0.0
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- transformers@2.1.0
  | +-- css@1.0.8
  | | +-- css-parse@1.0.4
  | | `-- css-stringify@1.0.5
  | +-- promise@2.0.0
  | | `-- is-promise@1.0.1
  | `-- uglify-js@2.2.5
  |   +-- optimist@0.3.7
  |   | `-- wordwrap@0.0.3
  |   `-- source-map@0.1.43
  +-- uglify-js@2.7.4
  | +-- async@0.2.10
  | +-- source-map@0.5.6
  | +-- uglify-to-browserify@1.0.2
  | `-- yargs@3.10.0
  |   +-- camelcase@1.2.1
  |   +-- cliui@2.1.0
  |   | +-- center-align@0.1.3
  |   | | +-- align-text@0.1.4
  |   | | | +-- kind-of@3.0.4
  |   | | | | `-- is-buffer@1.1.4
  |   | | | +-- longest@1.0.1
  |   | | | `-- repeat-string@1.6.1
  |   | | `-- lazy-cache@1.0.4
  |   | +-- right-align@0.1.3
  |   | `-- wordwrap@0.0.2
  |   +-- decamelize@1.2.0
  |   `-- window-size@0.1.0
  +-- void-elements@2.0.1
  `-- with@4.0.3
    +-- acorn@1.2.2
    `-- acorn-globals@1.0.9

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\tom\package.json'
npm WARN tom No description
npm WARN tom No repository field.
npm WARN tom No README data
npm WARN tom No license field.

Then checked to see if it worked by: jade --help

All looks good. till I get to compiling the code to HTML. 
On the command line I type: jade jadetut.jade

and it reads 

C:\>jade jadetut.jade

fs.js:893
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat 'C:\jadetut.jade'
    at Object.fs.lstatSync (fs.js:893:18)
    at renderFile (C:\Users\tom\AppData\Roaming\npm\node_modules\jade\bin\jade.js:227:17)
    at C:\Users\tom\AppData\Roaming\npm\node_modules\jade\bin\jade.js:136:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\tom\AppData\Roaming\npm\node_modules\jade\bin\jade.js:135:9)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

What am I doing wrong?? The path looks like the issue but I'm a nube and don't know what is going on...

**Comment by jamen** [comment]
Can you take this support question to [stackoverflow.com](https://stackoverflow.com/)? Those folks could probably help you better.  Seems like several things are wrong there, and I also don't use Windows.

P.S.: It is no longer `jade`, it was renamed to `pug`.  :smile:
