### ISSUE TITLE
In an include file or an inheriting source file, Can not read property 'test.hoge' of undefined

### ISSUE THREAD

**Issue by hitima** [gulp-community/gulp-pug#153]
I have a object variable,

test.pug
```
extends /_layout

-
  var page = {
  description_message: 'test'
  }

block container
  h1 #{page.description_message} // work this
  include /template/_future_page

```

_future_page.pug
```
h1 #{page.description_message} // not work this
```

```
    1|
> 2| h1(style=DESCRIPTION_COLOR) #{page.description_message}
    3|
    4|

Cannot read property 'description_message' of undefined
```

However, in an include file or an inheriting source file, Can not read property 'page.description' of undefined

Please, how can I solve this?

**Comment by hitima** [comment]
~~also working in jade.~~

**Comment by jamen** [comment]
Hmm.  I cannot see why this would be issue with `gulp-pug` specifically unless something changed im not aware about.

Can you try testing with something like `pug-cli` and see if you get the same effect?  If so, should probably report upstream to `pug`.

**Comment by hitima** [comment]
Thank you very much. I'm sorry, but it was impossible for jade. Is there any way of specifying something?

I will try it with pug-cli. Thank you very much.

**Comment by hitima** [comment]
When I search this object by console.log 
```
- console.log(page)
```
```
undefined
{ description_message: 'test' }
```

Is it a problem that you go to see the object before the object is defined? Is the inclusion timing too early? I do not know why console logs are spit twice.

However, by adding an if statement that it is not undefined, the expected object was taken.

```
  if (typeof(page) !== 'undefined')
    h1 #{page.description_message}
```

I could find a solution for the time being, but I hope to continue looking at behaviors such as pug-cli. (Because it does not seem to be the right way)

Thank you very much.

**Comment by phated** [comment]
I'm going to close this as outdated.  This module is just a tiny wrapper around pug so any issues are likely to be inside the core library.
