### ISSUE TITLE
Update pug

### ISSUE THREAD

**Issue by CydGoblin** [gulp-community/gulp-pug#158]
pug is now 2.0.0-rc.1, should this be updated on the package? alpha 2 was a long time ago

**Comment by demurgos** [comment]
The current version range picks the latest rc. I don't think we need to update the `package.json` file until the stable version is released.

**Comment by demurgos** [comment]
Fixed a few months ago in https://github.com/gulp-community/gulp-pug/commit/b6914231d1630995c612ab91c7345b303f107e0d
