### ISSUE TITLE
Mixing tabs and spaces seems to break gulp-pug

### ISSUE THREAD

**Issue by gluntn** [gulp-community/gulp-pug#164]
I was doing some editing with two different files (one had spaces, the other tabs), and it ended up with one of the files had tabs and spaces together. Trying to use gulp-pug does not print an error, it just says it has done what's it supposed to do and then quit

Is it normal behaviour?

**Comment by do100Han** [comment]
The result of using gulp-pug is an html document

2017-11-27 18:21 GMT+03:00 William <notifications@github.com>:

**Comment by demurgos** [comment]
I believe this is a Pug error: it does not support mixed indentation.

**Comment by phated** [comment]
Yeah, that's a pug thing. Closing this.
