### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by jamen** [gulp-community/gulp-pug#168]
Hey @pugjs/maintainers.  I dont use Gulp or Pug anymore. This was my only contribution so I'll be leaving. But there are who use it and shouldn't be left behind, so I'm dropping a notice.  This was one of my first endeavors in open source so I appreciate the opportunity.

**Comment by demurgos** [comment]
Hi, I am using this plugin for some time now and I am currently in the process of updating it (see #166, #167). I am not a member of @pugjs but I wouldn't mind giving a hand at maintaining this library. I already help maintaining a few libraries. `gulp-pug` is a library I depend a lot so I care about it being healthy.

**Comment by jamen** [comment]
Ping @hemanth @ForbesLindesay @phated

**Comment by phated** [comment]
I'm not a member of the org but I can vouch for @demurgos - he is part of the gulp team and focused on ecosystem health.

**Comment by ForbesLindesay** [comment]
@demurgos I've sent you an invitation to join the gulp-pug GitHub org. Ping me with a mention if you need anything else :)

**Comment by demurgos** [comment]
@ForbesLindesay 
Thanks: I did not have much time right now but I'll definitely help with maintaining this plugin.

You may also be interested in moving this repository to the [gulp-community](https://github.com/gulp-community) organization. You would keep ownership and control of the plugin (license, code style, npm publication) but it would benefit from easier maintenance by trusted Gulp contributors.

**Comment by ForbesLindesay** [comment]
I'm happy to do that/have that be done. I don't have permission to create repositories in the gulp-community so I can't transfer it at the moment.

**Comment by demurgos** [comment]
@phated 
According to [this article](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) the owner (or admin) of the original repo (@ForbesLindesay) must have repo creation permissions in the new organization (@gulp-community).

Could you help him with the transfer?

**Comment by phated** [comment]
Invitation sent

**Comment by demurgos** [comment]
Thanks @phated 
It seems that you are now the owner of `gulp-pug` so you should be able to do the transfer.

We still need to figure the best way to handle transfers.
