### ISSUE TITLE
Prevent jade from output includes

### ISSUE THREAD

**Issue by viviengarcia** [gulp-community/gulp-pug#17]
I haven't found any info about this : my includes are outputted as separate files (but they work, so this isn't a _real_ issue, just disturbing).
But isn't there any mean to just have the includes compiled into the files they're a part from ?

**Comment by viviengarcia** [comment]
Ok sorry about that, I've understand why it happened, that was me misusing your plugin. Issue closed.

**Comment by kylamedina** [comment]
@viviengarcia wait, can you point me to the answer? It's not obvious to me.

**Comment by viviengarcia** [comment]
@kylamedina Oh it was just me putting includes and "normal" files (i.e. index.jade) in the same folder. So includes was processed 2 times.

So by putting my includes in their own folder problem was solved. :)

**Comment by harrypujols** [comment]
You can also exclude files you don't want compiled by using a `not` operator. Example:

``` javascript
 return gulp.src(['file-you-want-compiled.jade', '!file-you-dont-want-compiled.jade'])
```

But I wonder how/if we can add the functionality of not compiling file names that start with an underscore, as with Sass? I believe Codekit does not compile Jade files that start with an underscore.

**Comment by viviengarcia** [comment]
I didn't know that, thx!

**Comment by harrypujols** [comment]
You are welcome. Note, that doesn't apply just to this plugin, but to any file you want excluded from a task regardless.

**Comment by viviengarcia** [comment]
Wow, that's even better! Is ist a node.js feature ?

**Comment by harrypujols** [comment]
It's just Javascript. You can write functions, use json, as in any Javascript file.

**Comment by viviengarcia** [comment]
Yeah, I don't know Javascript like I should. But I'm glad there are tools like gulp or node even if I don't really know how to use them in a very effective way. :)

**Comment by ghost** [comment]
Just wanted to add this for other people's references that may stumble upon this thread looking for an answer, you can use basic mini-match to exclude any files with an underscore:

```
gulp.task('jade', function() {
   gulp.src('/tpl/**/!(_)*.jade')
      .pipe(gulp.dest('/templates'))
});
```

The keyline is: `'/tpl/**/!(_)*.jade'`. It essentially searches recursively (`**`) through the `tpl` directly for all .jade files that don't have an underscore (`!(_)*.jade`).

**Comment by josecabana** [comment]
Thank you @dokether works like a charm!
