### ISSUE TITLE
Remove gulp devDependency

### ISSUE THREAD

**Issue by ghost** [gulp-community/gulp-pug#178]
Right now, gulp is only used for running `gulp-eslint`. It would be easier to run eslint directly. I can submit a PR if agreed.

**Comment by demurgos** [comment]
You're right: it would simplify things. I'll merge your other PR (#177) and do it myself since I'm working on this repo at the moment.

**Comment by ghost** [comment]
Alright.

**Comment by demurgos** [comment]
Gulp is still used to in the tests. I'm keeping it as a dev dependency but removing the gulpfile and `gulp-eslint` plugin in favor of a direct usage of `eslint`.
