### ISSUE TITLE
Write After End Error

### ISSUE THREAD

**Issue by Akkuma** [gulp-community/gulp-pug#18]
On the initial run the task has no problems. However, when I use gulp.watch the subsequent run of the task throws this error. I have two different tasks being watched and they seem to behave as expected with no error.

```
Error: write after end
    at writeAfterEnd (C:\Users\Greg Waxman\Documents\Git\stream-web\node_modules
\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_stream_writab
le.js:134:12)
    at Transform.Writable.write (C:\Users\Greg Waxman\Documents\Git\stream-web\n
ode_modules\vinyl-map\node_modules\through2\node_modules\readable-stream\lib\_st
ream_writable.js:182:5)
    at write (C:\Users\Greg Waxman\Documents\Git\stream-web\node_modules\gulp-ja
de\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:58
7:24)
    at flow (C:\Users\Greg Waxman\Documents\Git\stream-web\node_modules\gulp-jad
e\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:596
:7)
    at Transform.pipeOnReadable (C:\Users\Greg Waxman\Documents\Git\stream-web\n
ode_modules\gulp-jade\node_modules\through2\node_modules\readable-stream\lib\_st
ream_readable.js:628:5)
    at Transform.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (C:\Users\Greg Waxman\Documents\Git\stream-web\node_modules
\gulp-jade\node_modules\through2\node_modules\readable-stream\lib\_stream_readab
le.js:412:10)
    at emitReadable (C:\Users\Greg Waxman\Documents\Git\stream-web\node_modules\
gulp-jade\node_modules\through2\node_modules\readable-stream\lib\_stream_readabl
e.js:408:5)
    at readableAddChunk (C:\Users\Greg Waxman\Documents\Git\stream-web\node_modu
les\gulp-jade\node_modules\through2\node_modules\readable-stream\lib\_stream_rea
dable.js:169:9)
    at Transform.Readable.push (C:\Users\Greg Waxman\Documents\Git\stream-web\no
de_modules\gulp-jade\node_modules\through2\node_modules\readable-stream\lib\_str
eam_readable.js:131:10)
```

**Comment by andyscott** [comment]
I am having the same issue. How is this resolved?

**Comment by andyscott** [comment]
Gah! I figured it out. It was my mistake in reusing my pipe!

**Comment by OClement** [comment]
@andyscott Care to elaborate? I'm having the same error (in a different context) but knowing what your mistake was might help me (and others for sure) solve our own issues

Thanks

**Comment by juniorplenty** [comment]
@OClement Not sure if this is your issue, but I was getting this error when I was following the (erroneous) gulp-filter examples and creating filters outside of my task. So when watch triggered the task that used those filters, the filters were trying to re-use their internal pipes (I'm assuming,) hence the error.

Moving filter definitions (`var filter = filter('some/path')`) inside my task solved the problem.

**Comment by OClement** [comment]
@juniorplenty
Ooooh I am doing just that, would be great if it can be fixed with just this! Thanks, I'll try that tomorrow first thing in the morning!

**Comment by emirotin** [comment]
@juniorplenty thanks :)
I had a similar issue with a different plugin.

**Comment by gaving** [comment]
@juniorplenty :+1: cheers, that fixed my issues!

**Comment by OClement** [comment]
@juniorplenty Sorry for the very big delay before I got back here! 
Your solution did work perfectly, thanks for your help!

**Comment by hbin** [comment]
@juniorplenty You save a newbie to gulp!

**Comment by n8agrin** [comment]
This also helped me with gulp-filter. Non-obvious and really frustrating. Thank you!
