### ISSUE TITLE
How to compile new on changed files only (case with “includes” and “extends”)

### ISSUE THREAD

**Issue by ghost** [gulp-community/gulp-pug#182]
Thank you for the adaptation pug to gulp. 
In this issue, I want to consider the optimization aspect.

Consider the following file system:

📁 pug

　　test1.pug

　　test2.pug

　　　📁 partials

　　　　　partial1.pug

With gulp task

    gulp.task('pug', () => {
      return gulp.src('pug/*.pug')
      .pipe(pug())
      .pipe(gulp.dest('dist'))
    });

even we edit only **test1.pug**, both **test1.pug** and **test2.pug** will be compiled. If to change task to

    gulp.task('pug', () => {
      return gulp.src('pug/*.pug', {since: gulp.lastRun('pug')})
      .pipe(pug())
      .pipe(gulp.dest('dist'))
    });

since second 'pug' running by **gulp-watch**, changed or new files only will be passed. However, what if the `partial1.pug` has been included to `test1.pug`? (Assume that `gulp.watch` observes  all files).

**test1.pug**

    doctype html
    html
      head
        title Test 1
      body
        h1 Test 1
        include partials/partial1.pug

If we edit **test1.pug**, of course it will be compiled. However if we edit **partial1.pug**, test1.pug will not be passed by `{since: gulp.lastRun('pug')}`.

Can we do something to solve this problem?

**Comment by phated** [comment]
This is not a support forum. Please direct support questions to StackOverflow.

**Comment by ghost** [comment]
OK, I just leave the [link](https://stackoverflow.com/questions/50165810/gulp-pug-compile-new-on-changed-files-only-case-with-includes-and-extends) to same question in StackOverflow.
