### ISSUE TITLE
Adding gulp-pug-frontmatter-support to the "Also see" section

### ISSUE THREAD

**Issue by DougBeney** [gulp-community/gulp-pug#183]
Hello,
Just wanted to share a variation of this plugin I created called "[gulp-pug-frontmatter-support](https://github.com/DougBeney/gulp-pug-frontmatter-support)"

Using this plugin, this Pug code...

```pug
---
title: My Site
---

h1 Welcome!
```

...Will turn into this:

```html
---
title: My Site
---

<h1>Welcome!</h1>
```

This is useful for anyone who has a Gulp + Pug setup for a statically generated site. For example, I am using this in my [Jekyll-Bliss](https://github.com/DougBeney/Jekyll-Bliss) project.

I thought it might be useful to add this to the "Also see" list in your readme.

**Comment by phated** [comment]
The linked plugin goes against the gulpplugin ethos.  Instead of creating a fork and adding functionality, you should be thinking what sort of plugin you could create that would work in tandem with gulp-pug.

Example (this probably isn't the best API):
```js
gulp.src(...)
  .pipe(frontmatter.extract())
  .pipe(pug())
  .pipe(frontmatter.insert())
  .pipe(gulp.dest(...))
```

**Comment by DougBeney** [comment]
Gotcha. Will consider that.

**Comment by DougBeney** [comment]
Thanks for the feedback! I ended up taking your advice and created a separate plugin: https://github.com/DougBeney/gulp-frontmatter-wrangler

**Comment by phated** [comment]
@DougBeney awesome!  Feel free to submit a PR to the "Also see" section with your new module!
