### ISSUE TITLE
Gulp Pug on Linux

### ISSUE THREAD

**Issue by y4my4my4m** [gulp-community/gulp-pug#185]
I've recently moved my environment from OSX to Linux (Manjaro). 

My pug files properly compiles under OSX but won't on Linux. Running my task gives no error:
```
23:02:40] Using gulpfile ~/project/gulpfile.js
[23:02:40] Starting 'pug'...
[23:02:40] Finished 'pug' after 9.77 ms
```

However running npm gives me this warning message:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

I've searched online and they've mentioned this was a non-issue.
Does anyone know what's going on here?

**Comment by phated** [comment]
That has nothing to do with gulp-pug (it's the file watcher for OSX).

**Comment by y4my4my4m** [comment]
Ok, any idea why my pug files aren't compiling on linux?
