### ISSUE TITLE
Generate html files from pug using gulp in node js 

### ISSUE THREAD

**Issue by maiibraheem** [gulp-community/gulp-pug#186]
I'm creating a simple node js demo and I'm using pug
I need to use gulp to generate the html files 
I used gulp-pug but it didn't work as expected, it generated the same pug files again in the new directory

**My gulpfile.js was as below:**
// Gulp.js configuration
var gulp = require('gulp');
var pug = require('gulp-pug');
var watch = require('gulp-watch');

gulp.task('pug',function() {
 return gulp.src('views/*.pug')
 .pipe(pug({
    doctype: 'html',
    pretty: false
 }))
 .pipe(gulp.dest('/src/'));
});

gulp.task('watch', function () {
 return watch('views/*.pug', { ignoreInitial: false })
    .pipe(gulp.dest('pug'));
 });

**The result was:**
new folder named pug and inside it index.pug

**While I was expecting:**
new folder named src and inside it index.html

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
