### ISSUE TITLE
[question] how could I use client:true and require it in my javascript file

### ISSUE THREAD

**Issue by joneldiablo** [gulp-community/gulp-pug#187]
I want to use the html file compiled from pug as template for a jquery plugin something like:

´´´
const template = require('./template.js');
$(template)
....
´´´

where ./template.js is the pug compiled with ´client:true´

**Comment by joneldiablo** [comment]
nevermind, I have use gulp-wrapper, then append module.exports = template; to the file

**Comment by phated** [comment]
Yep!
