### ISSUE TITLE
Is it possible to compile with an external js file?

### ISSUE THREAD

**Issue by AlistairB** [gulp-community/gulp-pug#19]
Hi,

I want to compile and use data from an array in a separate JS file.

eg something like this

people.js

```
var people = ['john', 'mary', 'joe'];
```

people.jade

```
- each person in people
    .name #{person}
```

I want to do this because in my case the data is an array of complex objects and its nice to keep it separate.

**Comment by phated** [comment]
Read in your locals from those files and then pass them in as options.

people.js

``` js
var people = ['john', 'mary', 'joe'];
module.exports = people;
```

gulpfile.js

``` js
var jade = require('gulp-jade');

var jadeStream = jade({
  locals: require('./people')
});
```

**Comment by AlistairB** [comment]
Thank you. Not working for me though.

Do I need to include anything in my jade file to get access to people?

I am getting the error when I try and build

```
Cannot read property 'length' of undefined
```

when I try and access the array length

**Comment by AlistairB** [comment]
Figured it out. Should be:

```
module.exports.people = people
```
