### ISSUE TITLE
Load opts.data and opts.locals form *.json files

### ISSUE THREAD

**Issue by toptalo** [gulp-community/gulp-pug#194]
Hello!
I want to implement feature that allow us to define template data in separate json files.

For now, we can't use multiline data object definition in template file. So, I think, it will be better to use separate `*.json` files for this purpose.

It will be a global data json file for `opts.data` and for each page, we may create her own json file with same name as page have (example: `index.json` for `index.pug`).

I want to use same options names as used for passing data objects.

If type of `opts.data` is object - plugin will use it, if it is string then plugin will use it like path to json file.
For `opts.locals` string value will be taken as path to directory where stored json files with same name as page has.

if json data file does not exist, option will get an empty object.

Here is example of task config:
```javascript
var pug = require('gulp-pug');

gulp.task('views', function buildHTML() {
return gulp.src('views/*.pug')
    .pipe(pug({
        data: 'data/data.json',
        locals: 'data/',
        ...
    }))
});
```
What do you think?

**Comment by toptalo** [comment]
After opening issue I found `gulp-data`.

With config like this I can totally satisfy my needs
```javascript
gulp.task('test', function () {
    let globals = JSON.parse(fs.readFileSync('data/globals.json'));
    return gulp.src('./data/*.pug')
        .pipe(data(function (file) {
            let locals = JSON.parse(fs.readFileSync('data/' + path.basename(file.path) + '.json'));
            return Object.assign(globals || {}, locals || {});
        }))
        .pipe(pug())
});
```

**Comment by yukal** [comment]
If anyone still uses it in the projects, you can do it more carefully and elegant using a little trick with the [gulp-json-loader](https://github.com/yukal/gulp-json-loader)

**Comment by ShadowShahriar** [comment]
Thanks @toptalo and @yukal
