### ISSUE TITLE
Update test framework

### ISSUE THREAD

**Issue by demurgos** [gulp-community/gulp-pug#196]
> It might be worth revisiting the testing setup because it uses extremely outdated patterns and we could switch to something like Jest.

<https://github.com/gulp-community/gulp-pug/pull/195#issuecomment-490838827>

I am more familiar with Mocha (also used by Gulp core) but could take a look at Jest if you prefer. I agree that the test framework should be updated.

/cc @phated

**Comment by phated** [comment]
I've mostly used mocha with expect (but that module was taken over by jest). I'm probably going to explore jest for the next versions of gulp because everyone raves about it.  Have you noticed how gulp tests streams (using pipeline, concat, etc)?

**Comment by demurgos** [comment]
I haven't looked closely into Gulp tests: could you link to one of those streaming tests?

I have to admit that I had some issues with Mocha before, but I know it well so I was able to send them PRs or change my tests. I'll try to convert this package to use Jest so I can get a feel of it.

**Comment by phated** [comment]
Here's an example: https://github.com/gulpjs/vinyl-fs/blob/master/test/dest.js#L288-L310

**Comment by demurgos** [comment]
Jest uses different globals than Node. Node's `fs.readFileSync` errors are no longer `instanceof Error`. This further breaks inside `plugin-error` which checks for error objects using `instanceof Error`. This prevents `test/error.js` from working.

https://github.com/facebook/jest/issues/2549

In the issue above, [someone proposed a workaround](https://github.com/facebook/jest/issues/2549#issuecomment-423202304), but it's only a partial fix. There are similar issues with `Buffer` or `Array` values returned by builtin Node functions. This is a blocker for me.

I'll update the test framework to Mocha and expect. Once this issue is fixed, we can revisit using Jest: migrating from Mocha to Jest seems to be easier than from Tap to Jest.

**Comment by phated** [comment]
@demurgos sounds good!  Sorry you were the first to run into this for gulp stuff, as I haven't begun exploring it.

**Comment by phated** [comment]
@demurgos another note: gulp uses https://www.npmjs.com/package/expect version 1.20.2 (this has confused people in the past who've reached for the `expect.js` module)

**Comment by demurgos** [comment]
I am almost done with the conversion. I am using a style similar to `vinyl-fs`, it seems that error that happen inside the `assert` function (passed to `concat`) are not properly caught by Mocha. The test still fails, but I don't think `concat` passes the errors down.

**Edit**: I may be confused by the error messages generated by `expect` (I mostly use `chai`)

**Comment by phated** [comment]
@demurgos anything thrown inside the `assert` function will be caught by `mississippi.pipe` and handed to the final callback, which should be the `done` from mocha.  You'll likely want to use `mocha --async-only` so that a `done` callback is not missed accidentally.
