### ISSUE TITLE
How to browse errors with gulp-pug ?

### ISSUE THREAD

**Issue by AntonGrekov** [gulp-community/gulp-pug#205]
I am using gulp-pug v4
Errors shown in this way:

[22:55:23] Starting 'pug'...
[22:55:23] Finished 'pug' after 2.28 ms
[22:55:23] Starting 'reloadHTML'...
[22:55:23] Finished 'reloadHTML' after 643 μs
[22:55:23] Unexpected token (289:5)

289 is a line number in concatinaited pug file after insterting all includes, blocks etc

How to switch it to more verbose way ?

**Comment by demurgos** [comment]
I don't believe it is currently available. An error formatting/reporting option would be nice.

**Comment by phated** [comment]
The error should be shown before `Finished 'pug' after 2.28 ms`, so you'll probably need to include more information, such as your gulpfile, for this to be helpful.
