### ISSUE TITLE
Client single file?

### ISSUE THREAD

**Issue by caiodv** [gulp-community/gulp-pug#21]
Is there any way I can compile all my .jade templates as {client:true} into a single file with different function names?
So far I got them compiled into a single file using concat, but they all output as template().

gulp.src("templates/*_/_.jade")
    .pipe(jade({client: true}))
    .on('error', console.log)
    .pipe(concat("templates.js"))
    .pipe(gulp.dest("../website/js"))

turns into

function template(locals) {
var buf = [];
var jade_mixins = {};

buf.push("<div class=\"test\"></div>");;return buf.join("");
}
function template(locals) {
var buf = [];
var jade_mixins = {};

buf.push("<div class=\"anotherTest\"></div>");;return buf.join("");
}

**Comment by phated** [comment]
You are going to have to use some other gulp plugin to handle that use case.  This is outside the scope of the gulp-jade module.

I am unaware of any plugins that might help you.  Try looking for a namespace plugin or something similar.
