### ISSUE TITLE
Self closing tags not being applied

### ISSUE THREAD

**Issue by dippas** [gulp-community/gulp-pug#214]
In Pug engine, the self closing tags are working as expected

for instances:

PUG

```
img
```
in HTML

```
<img />
```

but then using `gulp-pug`, it does this:

  PUG

```
img
```
in HTML

```
<img>
```

**Comment by phated** [comment]
What version of `pug`? I noticed that #207 is requesting a new version.

**Comment by dippas** [comment]
@phated  both v2 and v3 

v2: https://pugjs.org/api/migration-v2.html#selfclosing
v3: https://pugjs.org/language/tags.html

related : https://github.com/pugjs/pug/issues/2875 (this is for v1)

Apparently changing `doctype html` to `doctype html5` it works, but the latter is not a standard doctype - [w3c doctype list](https://www.w3.org/QA/2002/04/valid-dtd-list.html)

**Comment by dippas** [comment]
@phated with v5 released this has been fixed . Thank you ;)

**Comment by phated** [comment]
Thanks for checking!
