### ISSUE TITLE
Error message in not easy to understand

### ISSUE THREAD

**Issue by smallma** [gulp-community/gulp-pug#223]
when we use gulp-pug to transfer pug to html, the error messages are always not easy to understand. how to improve it? I need the detail to fix issue. But right now the error message is too rough to tracking . Thanks.

![截圖 2021-07-09 上午11 36 50](https://user-images.githubusercontent.com/429250/125019661-03ef2b00-e0aa-11eb-9549-0da855be3fa4.jpg)

**Comment by phated** [comment]
These are just pug errors.

**Comment by smallma** [comment]
of course pug error. but there is no any useful message to show up where the problem is. Do you know how to show more info?
