### ISSUE TITLE
[Question] #{__('home')} where __ is not a function

### ISSUE THREAD

**Issue by sabatale** [gulp-community/gulp-pug#224]
Hello,

I'm starting to get into gulp and probably have a silly question.

While using i18n helpers (`#{__('home')}`), I get the following error from gulp-pug:

`__ is not a function`

Now I'm guessing the interpreter is not recognizing the pattern from i18n-node.

Is there an option I missed to ignore that pattern?

Thanks!

**Comment by phated** [comment]
This isn't an issue with gulp-pug. It's either a user error or something with pug itself. Please refer to that project.
