### ISSUE TITLE
[11:15:28] Error in plugin "gulp-pug" when i do compile:all

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [gulp-community/gulp-pug#225]
i tried **compile:all**

Message:
    ENOENT: no such file or directory, open '/home/linux/Documents/NR/sparrow-2.0.2-and-sparrow-1.7.1/s/src/pug/mixins/common/card.pug'
    at /home/linux/Documents/NR/sparrow-2.0.2-and-sparrow-1.7.1/s/src/pug/layouts/LayoutDocumentation.pug line 3
Details:
    errno: -2
    syscall: open
    code: ENOENT
    path: /home/linux/Documents/NR/sparrow-2.0.2-and-sparrow-1.7.1/s/src/pug/mixins/common/card.pug
    domainEmitter: [object Object]
    domainThrown: false

**Comment by phated** [comment]
Support questions should be asked on stackoverflow or gulpjs discussions.
