### ISSUE TITLE
Compile and render at same time (HTML and javascript)

### ISSUE THREAD

**Issue by pszabop** [gulp-community/gulp-pug#226]
I'm working on HTML emails and I need to be able to generate HTML so I can preview what my email will look like (using browsersync) as well as generate javascript to be used to render the HTML in my node application.

I don't want to generate two completely different build pipelines, but that appears to be what I need to do right now.

The idea would be to have gulp-pug generate both render and compile outputs at the same time and then use fork-pipe to put the two different outputs in appropriate locations:

https://www.npmjs.com/package/fork-pipe

The feature request is "an option flag to both compile and render at the same time"

**Comment by phated** [comment]
That is outside of the scope of this project (and plugins in general). You should use gulp plugins and other stream utilities to build composable pipelines.
