### ISSUE TITLE
Accept locals from stream

### ISSUE THREAD

**Issue by jordanthomas** [gulp-community/gulp-pug#25]
I'm using gulp-front-matter to define some locals (page title, etc). Some code to illustrate what I'm doing (well, trying to do):

```
gulp.task('pages', function() {
  return gulp.src(paths.pages)
    .pipe(frontMatter({ property: 'data' }))
    .pipe(jade({ pretty: true }))
    .pipe(gulp.dest('build'))
});
```

Would having gulp-jade check for a `locals` or `data` property on the incoming `file` object and using it for the jade render be a crazy feature request?

I came up with this to see if it was feasible. If it looks sane I can put a PR together, if you'd like.

```
function CompileJade(file, enc, cb){
  opts.filename = file.path;
  file.path = handleExtension(file.path, opts);

  if ('data' in file) {
    opts.locals = file.data;
  }

  if ('locals' in file) {
    opts.locals = file.locals;
  }

  ...
}
```

**Comment by Delapouite** [comment]
I encountered the exact same issue. Optionaly reading the _locals_ variable (or a configurable name as in the front matter plugin) of the vinyl object would be a very nice addition.

**Comment by Delapouite** [comment]
@jordanthomas With your solution, if locals are provided by the front matter plugin on the vinyl object, they overwrite locals provided in the regular options object. Let me extend your example :

``` js
gulp.task('pages', function() {
  return gulp.src(paths.pages)
    .pipe(frontMatter({ property: 'locals' }))
    .pipe(jade({ pretty: true, locals: {foo: bar} }))
    .pipe(gulp.dest('build'))
});
```

In this scenario, _foo = bar_ would never be accessible for jade to render.
So they should be some kind of merge locals from the vinyl object and the one passed as options.

But which one should take precedence in case of key name conflicts? For instance, if in the frontMatter data there's _foo = qux_, should it win or lose over _foo = bar_?

**Comment by jordanthomas** [comment]
@Delapouite My gut reaction would be that data coming in from Front Matter would trump that provided to Jade. That said, I'm not sure there's a _right_ answer.

**Comment by phated** [comment]
I've thought a lot about this and this seems way too specific and coupled to front matter so I don't plan to add this to gulp-jade.  On the same subject, I think your use of front matter in jade templates is the wrong approach.  You can already define objects in jade, so putting in comments and parsing them into an object seems like an unnecessary and confusing step.

**Comment by Delapouite** [comment]
Ok. So I guess a new plugin is needed, transforming front-matter headers into their equivalent jade var declarations conterparts :

```
---
title: Post title
category: JS
----
body
    h1= title
```

to

```
- var title = 'Post title'
- var category = 'JS'
body
    h1= title
```

**Comment by koistya** [comment]
@Delapouite, yeah, that would be nice!

**Comment by Delapouite** [comment]
@koistya you can have a look at https://github.com/lmtm/gulp-front-matter for inspiration
