### ISSUE TITLE
markdown file to jade template

### ISSUE THREAD

**Issue by ghost** [gulp-community/gulp-pug#28]
Hi! Sorry if this is a noob question.

I'm looking for a way to pass a raw markdown file to a block of a Jade template with Gulp. I've found this plugin [gulp-static-site](https://www.npmjs.org/package/gulp-static-site) which it does what I'm looking for. But the [gulp plugin list](http://gulpjs.com/plugins/) says that it's a duplicate of gulp-jade.

Well... how can I handle to do that with gulp-jade

**Comment by vidakovic** [comment]
I have a similar problem including external markdown files. In my previous grunt setup I could do something like this:

include ..some/where/content.md

Would be extremely handy if this worked with gulp-jade... not sure how much work it is.

**Comment by phated** [comment]
@vidakovic I made the grunt-jade plugin and it never did that. The gulp-contrib-jade plugin might have but grunt plugins are notorious for doing too many things so gulp-jade won't be following suite.

@irgstudio sorry I missed this previously.  The gulp-static-site module has been rewritten with better documentation and has been un-blacklisted as per https://github.com/gulpjs/plugins/issues/112 and https://github.com/gulpjs/plugins/pull/113
