### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by yocontra** [gulp-community/gulp-pug#3]
Also you don't need to use clone() anymore

**Comment by phated** [comment]
Should be able to pipe to https://github.com/phated/gulp-wrap-amd

**Comment by yocontra** [comment]
Oh nice I didn't even see that. You should drop a link in the README so others catch it.

**Comment by phated** [comment]
Note added in https://github.com/phated/gulp-jade/commit/55b8df27f3f51f6405feebd710627fb55ecce6a2
