### ISSUE TITLE
HTML Compilation Error

### ISSUE THREAD

**Issue by ridgehkr** [gulp-community/gulp-pug#34]
When following up an HTML element with plain text, the text fails to be contained within its parent element, which instead gets closed and then re-opened after its children. This error does not reproduce on the [demo page](http://jade-lang.com/demo/) for the Jade language, so I suspect that the issue could be fixed by a simple compiler upgrade.

source:

``` jade
p
    figure
        img(src='#', alt='')
        figcaption image caption text
    | This text and the element before it does not get wrapped by the paragraph element.
```

result:

``` html
<p></p>
<figure><img src="#" alt="">
    <figcaption>image caption text</figcaption>
</figure>
This text and the element before it does not get wrapped by the paragraph element.
<p></p>
```

**Comment by phated** [comment]
The latest gulp-jade uses the [newest jade](https://github.com/visionmedia/jade/releases/tag/1.3.1)
