### ISSUE TITLE
Add filter option

### ISSUE THREAD

**Issue by geedmo** [gulp-community/gulp-pug#36]
Could be possible to add an option to use custom jade filters? Or expose the internal jade reference instead?

Great work, thanks!

**Comment by phated** [comment]
You should be able to install `jade` at the same level as `gulp-jade` and as long as it satisfies the dependency range, it will be used for compilation.  You can then attach filters to  `require('jade').filters` (or whatever the syntax is) that will be applied.

`npm install jade gulp-jade` should solve the problem.

**Comment by geedmo** [comment]
Thanks for your reply @phated.
Solution:

```
var jaderef = require('gulp-jade/node_modules/jade'),`
```

It would be more elegant accessing to the jade instance in "gulp-jade" because including jade separately doesn't work due to filters should be performed on the object that compiles the source code.
