### ISSUE TITLE
Adding support for function-typed locals data?

### ISSUE THREAD

**Issue by fritx** [gulp-community/gulp-pug#37]
Ref: https://github.com/visionmedia/jade/issues/1497#issuecomment-48495808

In grunt, we could provide a function like `function (dest, src) {}`
And I think in gulp, we can support one like `function (file) {}`
Thanks.

``` js
gulp.task('jade', function(){
  gulp.src('xx')
  .pipe(jade({
    data: function(file){
      return {
        name: path.basename(file.path)
      }
    }
   }))
  .pipe(gulp.dest('xx'))
})
```

**Comment by phated** [comment]
We already support this use case by supporting data passed on vinyl objects from a module like gulp-data.  Please see https://github.com/phated/gulp-jade#use-with-gulp-data

**Comment by fritx** [comment]
Oic, thanks!
