### ISSUE TITLE
Option to Log compiled files ?

### ISSUE THREAD

**Issue by antoniobrandao** [gulp-community/gulp-pug#40]
Hello,

Is there an option to output the name of the compiled files in the terminal log?

I tried passing { debug: true } but that's something completely different.

I hacked node_modules/gulp-jade/node_modules/jade/lib/jade.js, added this line in line 107

gutil.log('[gulp-jade] compiled ' + parser.filename);

And now I get the desired log entries such as:

[18:25:20] [gulp-jade] compiled /Users/antoniobrandao/WEBROOT/site/public/team.html

But this hack obviously will vanish as soon as I make any update. And the rest of the team can't get it from NPM. Making a Fork just for this wouldn't make sense either. 

So is there such option ? If not, could it be soon / one day ?

Thanks

**Comment by phated** [comment]
I don't want to add extraneous logging to this plugin.  Have you tried something like [gulp-debug](https://www.npmjs.org/package/gulp-debug/) as it seems like you would only want this while debugging a stream or in a development environment (you could combine it with gulp-if)

**Comment by antoniobrandao** [comment]
Hello,

Thanks for answering! Gulp-debug outputs a little bit too much information (debug info), clutters the console a bit, and doesn't provide an option to simply print the name of the compiled file to the console, which is handy very often..
