### ISSUE TITLE
Catch errors without stopping gulp.watch

### ISSUE THREAD

**Issue by artem-malko** [gulp-community/gulp-pug#41]
I've seen, you've got the same issue, but i still has this problem.
Could you help me, how can i repair it?

Mac OS 10.9.4
NodeJS 0.10.26
I use last version of gulp-jade

**Comment by phated** [comment]
This is a problem with gulp.watch, not gulp-jade. It is something that is being looked into for gulp4

**Comment by lolmaus** [comment]
Is there a recommended method to recover from errors?

Here's what i'm trying to do:

``` js
//...
.pipe(
  jade()
    .on("error", gutil.log);
)
//...
```

This prevents the watch from stopping, but the Jade task will not recompile until i restart Jade. :(

@phated, can you please suggest a workaround?

**Comment by artem-malko** [comment]
@lolmaus here you are)

``` js
.pipe(jade({
    pretty: true,
}))
.on('error', notify.onError(function (error) {
    return 'An error occurred while compiling jade.\nLook in the console for details.\n' + error;
}))
```

Use gulp-notify for this. This will catch errors and recompile jade templates after errors.

**Comment by lolmaus** [comment]
Thank you, @artem-malko.

**Comment by felipebernardes** [comment]
Thanks, @artem-malko !

**Comment by illuminos** [comment]
The following code might be even better
```javascript
.pipe(plumber())
.pipe(plumberNotifier())
.pipe(pug())
```
Provided you have gulp-plumber and gulp-plumber-notifier installed. Makes for a much better user experience.

**Comment by lucianobarauna** [comment]
Thanks, @artem-malko !

**Comment by kiditran** [comment]
thank @artem-malko
