### ISSUE TITLE
gulp-jade is not working

### ISSUE THREAD

**Issue by artem-malko** [gulp-community/gulp-pug#42]
I've just updated gulp-jade after your last commit and it's not working. 
I've got index.jade, with some code and several includes. Task works without errors, but index.html is empty.
I've tried it on Mac, on Windows and Ubuntu 12.04. Result is the same always.
I think, there is a problem with jade 1.5, cause gulp-jade version 1.3 works correctly.

**Comment by phated** [comment]
There were no changes except updating jade.  I am assuming something is wrong with that package or your index.jade.  Please open an issue there or revert to the prior version of gulp-jade.
