### ISSUE TITLE
Option to compile multiple client templates into one object

### ISSUE THREAD

**Issue by scottcheng** [gulp-community/gulp-pug#44]
Thanks for this great plugin!

I would like to have the ability to compile multiple client-side templates into one object in one file. For example, I have `foo.jade` and `bar.jade`, and if I do

``` javascript
gulp.src(['foo.jade', 'bar.jade'])
  .pipe(jade({ client: true })
  .pipe(gulp.dest(...));
```

I would like the resulting file to define an object (say `JST`), which has two methods `foo` and `bar` corresponding to the two templates. Then I can use the templates with `JST.foo(locals)` and `JST.bar(locals)`.

[grunt-contrib-jade](https://github.com/gruntjs/grunt-contrib-jade) supports this.

Thanks!

**Comment by phated** [comment]
I think you are looking for https://www.npmjs.org/package/gulp-declare/ + https://www.npmjs.org/package/gulp-concat/

See usage information in gulp-declare for combining the 3 modules (replace handlebars with jade)

**Comment by scottcheng** [comment]
Beautiful. Thanks!
