### ISSUE TITLE
Is it possible compile only changed file?

### ISSUE THREAD

**Issue by lichtner** [gulp-community/gulp-pug#45]
``` coffee
gulp.task 'jade', ->
  gulp.src 'app/views/*.jade'
    .pipe gulpJade({pretty: true})
    .pipe gulp.dest('tmp/views')
```

this compile all files despite I change only one jade file.

**Comment by phated** [comment]
Don't glob on file change, just pass the single filename of the changed file to `gulp.src`

**Comment by NeXTs** [comment]
@phated Hi Blaine!

> just pass the single filename of the changed file to gulp.src

Could you please share some pseudo-code example how to do that?
How to determine only changed file in watch task and pass it to gulp.src?

**Comment by NeXTs** [comment]
Okay, I see.

```
gulp.watch('smth').on('change', function(event) { //event.path })
```

But it will not update parent files if changed file was included, now I see why gulp-jade rerenders all files..
