### ISSUE TITLE
1.0 and stability: locked

### ISSUE THREAD

**Issue by phated** [gulp-community/gulp-pug#60]
Now that we accept custom jade instances, I don't know if there are any reasons to add extra features to this.  If nothing comes up before the next jade release, I will be bumping this to 1.0 and locking the API.

**Comment by phated** [comment]
Jade released. Does anyone think this shouldn't be API frozen?

**Comment by bsr203** [comment]
Thanks for the option to use custom jade, current API works great for me.

**Comment by phated** [comment]
Only hangup on this is #72

**Comment by phated** [comment]
Done and done. Publishing as soon as the tests run.
