### ISSUE TITLE
Mention the Jadeify transform.

### ISSUE THREAD

**Issue by EvanCarroll** [gulp-community/gulp-pug#61]
I had a real bear of a time getting gulp-jade to work. To get the module to commonjs for use with browserify I tried,

```
 var jade = require('gulp-jade');
 gulp.task('jade', function() {
       gulp.src('views/client/*.jade')
       .pipe(jade({
               client: true,
       }))
       .pipe(wrap('commonjs', {require: {jade:'jade'}}))
       .pipe(gulp.dest('./build/templates/'))
});
```

Though this made the Javascript a commonjs module that could be included.. It still didn't work in browserify. When I used a variable in a template it threw an error complaining that Jade was undefined when it tried to resolve Jade.escape.

Anyway, I ended up using the Jadeify transform with browserify. If you're using browserify this is an all around better less-hacky idea. Perhaps we should update the docs and refer those browserify users to the [Jadeify transform.](https://github.com/domenic/jadeify)

**Comment by phated** [comment]
Sorry you were having such a difficult time but I don't see the point of adding that to the README here as this library has nothing to do with browserify and browserify has it's own plugin system (transforms).  That is the first thing browserify users should try, not some weird hacky mix of gulp and browserify.

**Comment by EvanCarroll** [comment]
I imagine most everyone that uses gulp uses browserify. Moreover, I imagine that most of the people that use clientjs and a streaming buildsystem are using browserify. Anyway, I just think the users would stand to gain something with a reference to another module that has quite an overlapping usecase.

**Comment by phated** [comment]
That isn't a problem I need to solve with a README on a **completely** separate project.  This has nothing to do with browserify.

**Comment by EvanCarroll** [comment]
Yea, documentation isn't something you have to do when it leaves people who would be better served by someone else's module to use your own.

**Comment by phated** [comment]
I am sorry that you don't understand how browserify works. I would suggest finding some well written blog posts instead of complaining on an unrelated module. Locked.
