### ISSUE TITLE
Not working option pretty: '\t'

### ISSUE THREAD

**Issue by zoxon** [gulp-community/gulp-pug#65]
The Jade API documentation says that I can use '\t'. But it doesn't work
http://jade-lang.com/api/

My gulp task code

``` js
gulp.task('jade', function() {
    gulp.src(path.html.source)
        .pipe(jade({
            pretty: '\t',
            basedir: path.html.basedir
        }))
        .on('error', handleError)
        .pipe(gulp.dest(path.html.destination))
});
```

**Comment by phated** [comment]
This is because those options were added in version 1.8. You can pass a custom version of jade as the jade option

**Comment by zoxon** [comment]
@phated Please tell me how to do it. If possible with example. 
Thank you

**Comment by bsr203** [comment]
@Zoxon  it is described in https://github.com/phated/gulp-jade#options

**Comment by zoxon** [comment]
Thank you. Everything works, only plus one extra module must be installed. Wouldn't it be easier to upgrade the version of jade in the gulp-jade?

**Comment by bsr203** [comment]
In one another issue @phated mentioned the reason. He want to make sure all tests passes, etc for even for minor version changes as jade doesn't guarantee stability between changes. It may be considerable effort for him to do the keep up with minor changes, and I am glad we have an option to use it with latest version.

**Comment by phated** [comment]
As always, I am willing to take a PR with the jade update with fully passing tests.  This module is in maintenance mode and I don't do anything on it anymore, but I will always take a look at PRs.
