### ISSUE TITLE
Better error logging?

### ISSUE THREAD

**Issue by hutber** [gulp-community/gulp-pug#66]
I must admit I am unsure if this is something you can effect or is a problem with jade. 

But I currently have the simplest of jade files 

**Jade File**

``` javascript
.header jamie
```

**Gulp task**

``` javascript
gulp.task('jade', function () {
    return gulp.src('./frontend/views/**/*.jade')
        .on('error', handleErrors)
        .pipe(jade({
            client: true
        }))
        .pipe(gulp.dest('frontend/js/jade'));
});
```

**Error**

```
[23:50:27] gulp-notify: [Compile Error] Unexpected token
```

**Compiled Jade**

``` javascript
function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;

buf.push("<div class=\"header\">jamie</div>");;return buf.join("");
}
```

The funny thing is, first running this task it compiles, hence the above compiled. But it still gives the error. Then when changing the file it won't compile with the same error `Unexpected token`

Would it be possible to have more information about the kind of error?

**Comment by phated** [comment]
Where is gulp-notify in this flow?

**Comment by hutber** [comment]
Sorry to have taken up your time as this for sure isn't your problem. This is the full error:

``` javascript
[
  C:\var\www\mywarhammer.co.uk\frontend\views\home.jade:1
  .header
  ^
  ParseError: Unexpected token ]
```

Unless you've got spare random time, I'll take this question to a Q&A site :+1:
