### ISSUE TITLE
gulp-jade not throwing errors

### ISSUE THREAD

**Issue by bakpa** [gulp-community/gulp-pug#67]
It seems like errors are not being thrown when they should. 

When I enter a line like this into one of my templates:
h1
  This is copy in an header

My assumption is that I should be thrown an error. Here is my current code:

.pipe(jade({
      compileDebug: true
    }))
    .on('error', function(err) {
      util.log(err);
    })

Thanks for the help.

**Comment by phated** [comment]
Can you create an actual repo that I can run?

**Comment by bsr203** [comment]
@bakpa  the way it works for me is to set the event reg on jade as

```
    .pipe($.jade(config.options).on('error', handleErrors))
```

not on gulp stream (outside)

**Comment by phated** [comment]
@bsr203 thanks.  closing.
