### ISSUE TITLE
Jade version

### ISSUE THREAD

**Issue by Blaze34** [gulp-community/gulp-pug#68]
Why You not use latest jade version?
From dependencies:
"jade": "1.1 - 1.7"
but now available jade 1.8.2

**Comment by phated** [comment]
see https://github.com/phated/gulp-jade/issues/65#issuecomment-66173432

We are contemplating freezing API on the next bump which will include a jade dep update. I don't trust jade to follow semver, so we bump and run all the tests before publishing.

**Comment by phated** [comment]
Published as 0.11.0.  Supports jade through 1.9
