### ISSUE TITLE
Handle logs

### ISSUE THREAD

**Issue by yocontra** [gulp-community/gulp-pug#7]
There should be an option to suppress these https://cloudup.com/cIDvjvTcWE2

**Comment by phated** [comment]
This might be related to the `debug` option. Can you add give me an example file to run against?

**Comment by yocontra** [comment]
@phated This happens with any jade file that emits warnings. We have some complicated mixins that cause this problem - I'll see if I can tease them out for a repro

**Comment by phated** [comment]
There doesn't seem to be a way to do this currently.

I added an issue at https://github.com/visionmedia/jade/issues/1395

Closing.
