### ISSUE TITLE
running test with `npm test` issue

### ISSUE THREAD

**Issue by ifraixedes** [gulp-community/gulp-pug#70]
When I've been executing the tests for the PR #69 I've realised that running `npm test` the console output related with tap is

```
total ................................................... 0/0
```

Hence no test is executing; it may a problem with dev environment, but I haven't found what it may be; my work around has been executing the test scripts with `node test/<<filename.js>>`

**Comment by phated** [comment]
I believe it's a problem with your development environment.  See https://travis-ci.org/phated/gulp-jade
