### ISSUE TITLE
gulp-jade task is taking much longer than it displays

### ISSUE THREAD

**Issue by noahgrant** [gulp-community/gulp-pug#71]
I can't really tell if this is a jade issue or a gulp-jade issue, so I figured I'd start here.

when I run `$ gulp jade`, it says my jade task finishes after 7.8ms! Super fast!  And you know, when I'm only changing one file, that's accurate. However, when I run the entire jade task, the process keeps running for about 7-8 seconds after it told me the task had finished.  I am using includes and extends, which I'm sure slows it down, but (a) that seems like a long time to compile only about 30 templates or so, and (b) why doesn't the process stop after the task is complete?

relevant code, pretty straightfoward:

``` js
gulp.task('jade', function() {
  gulp.src(sources.jade)
    .pipe(gulpif(dev(), plumber()))
    .pipe(jade())
    .pipe(gulp.dest('./dist/'));
```

do you have any insight into this?  Is it on the gulp-jade wrapper side or with jade itself?

Thank you!!

**Comment by phated** [comment]
Return your streams. You currently aren't using gulp correctly.

**Comment by noahgrant** [comment]
FML THANK YOU

**Comment by noahgrant** [comment]
Can you explain why that fixed my issue? The [gulp docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support) say that I should return streams only if I want to run things asynchronously, but it's not obvious from my task that anything there is asynchronous.  Furthermore, the docs also say that I could make it async by [invoking a callback](https://github.com/gulpjs/gulp/blob/master/docs/API.md#accept-a-callback) passed to the task function, but that actually didn't work for me (i initially tried it that way).
