### ISSUE TITLE
extend file data with locals

### ISSUE THREAD

**Issue by olanod** [gulp-community/gulp-pug#72]
The context passed to a jade template is either the locals object or the data object (`opts.compile(contents, opts)(opts.locals || opts.data)`). It would be better if its the combination of both.  
My use case is, I use gulp-data to read a json file with the strings of my template(for translating templates) and I also use the locals object to set `{dev: true}`.

**Comment by phated** [comment]
I think that would lead to more problems than it solves.  Let's see what other people have to say.  Btw, you can use `gulp-data` with a callback to attach your `dev` property.

**Comment by shinnn** [comment]
- As @phated said, I always use gulp-data to [deeply extend](https://github.com/unclechu/node-deep-extend) locals with file.data and that will do. But I think it's more helpful that gulp-jade take it on.
- Though @olanod titled this issue `extend file data with locals`, the behavior I expected is `extend locals with file data`.

**Comment by phated** [comment]
@shinnn if there is an easy way to opt-in to this behavior, why do you think we should include it in the core of this module?  Deeply extending is expensive and would have to happen on each file through the stream which seems bad for default behavior.

**Comment by shinnn** [comment]
@phated I didn't care about the case when the project has many `.jade` files. OK, now I don't think gulp-jade doesn't have to include extending behavior. I'll continue using gulp-data in that case.

**Comment by phated** [comment]
@shinnn could you send a PR documenting your usage of gulp-data + extending in the Readme? I think that would suffice for this.

**Comment by shinnn** [comment]
@phated Sure. Is it urgent?

**Comment by phated** [comment]
@shinnn nope, just whenever you have a spare moment.  Thanks!

**Comment by phated** [comment]
I've added an example in the gulp-data section on how to extend your dynamic data with locals.
