### ISSUE TITLE
The case when the file object doesn't have `path` property

### ISSUE THREAD

**Issue by shinnn** [gulp-community/gulp-pug#74]
I know it's the very, very edge case, but vinyl file object does not always have `path` property.

In such a case, I think gulp-jade should (1) set a temporary `filename`, or (2) emit an error.

**Comment by phated** [comment]
That seems really weird.  Why would a vinyl object not have a path?

**Comment by shinnn** [comment]
For example, the vinyl object is created using [vinyl constructor](https://github.com/wearefractal/vinyl) without `path` option, the object doesn't have `path` property.

``` js
var File = require('vinyl');

var file = new File({
  contents: new Buffer('foo')
});

file.path; //=> undefined
```

> I know it's the very, very edge case

**Comment by phated** [comment]
K.  I don't think this is something every plugin should have to manage.  It falls upon the lines of piping a `.js` file to a CSS beautifier.  If the end-user is doing something like this, they should use `gulp-rename` or `gulp-if` to deal with that edge case.

**Comment by shinnn** [comment]
> they should use `gulp-rename` or `gulp-if` to deal with that edge case.

You're right.
