### ISSUE TITLE
gulp-jade quits without finishing task?

### ISSUE THREAD

**Issue by codebling** [gulp-community/gulp-pug#79]
I have the following gulp task:

```
gulp.task('jade', function(done) {
  gulp.src(paths.jade)
    .pipe(data(function(){}))
    .pipe(jade())
    .pipe(gulp.dest('./www/templated/'))
    .on('end', done);
});
```

Which is trying to compile this jade file:

```
#{anything}
```

But when I try to run the task, the jade task quits without finishing:

```
$ gulp jade
[14:39:24] Using gulpfile ~/path/gulpfile.js
[14:39:24] Starting 'jade'...

$
```

Apologies in advance if I've missed something obvious here. I can't tell if this is a gulp-jade issue, or quite what I am doing wrong. It looks as if there is surpressed error.

**Comment by phated** [comment]
This isn't a bug in gulp-jade.  Please post support questions to stackoverflow.

**Comment by codebling** [comment]
Thanks. Should have done that first.
