### ISSUE TITLE
Disable html minification

### ISSUE THREAD

**Issue by yocontra** [gulp-community/gulp-pug#8]
Possible or does jade do this as a part of the compilation process?

**Comment by gisu** [comment]
Try this

``` javascript
gulp.task('jade', function(){
  gulp.src(['src/jade/*.jade','!src/jade/_*.jade'])
  .pipe(jade({
      pretty: true
    }))
  .pipe(gulp.dest('tmp/'))
});
```

**Comment by phated** [comment]
I think I could change the `pretty` option to `true` by default, incase someone wants to pipe to a different HTML minifier, but I disagree with disabling options allowed by the compiler (see [gulp-less](https://github.com/plus3network/gulp-less#options))

**Comment by phated** [comment]
On 2nd thought, I think relying on the Jade defaults is the best choice.  It reduces code complexity and doesn't confuse users.
