### ISSUE TITLE
How to keep trailing whitespace

### ISSUE THREAD

**Issue by jansensan** [gulp-community/gulp-pug#82]
Currently, when using gulp-jade to compile a template into HTML, this

```
p
  span This is the first part of the sentence, 
  strong this part makes a strong point, 
  span and this part concludes the sentence.
```

loses its trailing whitespace. I currently opened [a StackOverflow question](http://stackoverflow.com/questions/29276580/how-to-keep-trailing-whitespace-with-gulp-jade) with more details about this.

If I understand the Jade documentation properly, the trailing whitespace should not be removed. Is there an issue with gulp-jade, or is there an undocumented gulp-jade option that would allow to keep some whitespace?

**Comment by phated** [comment]
We don't do any modification of the results from jade.  Stackoverflow or the jade repo are probably the places to ask.
