### ISSUE TITLE
When crashing with plumber, jade task is killed

### ISSUE THREAD

**Issue by iduuck** [gulp-community/gulp-pug#83]
Currently I have the following problem: When I am including an partial and an compilation error comes up, the task is killed and does not update when the file is changing again. I am already using plumber.

**Comment by iduuck** [comment]
**Correction:** The task is just not finishing and hanging in a "loop"..

**Comment by phated** [comment]
Not sure what you want me to do.  This plugin is written just like every other one, so it's not a problem with this module.  gulp-plumber is a hack on streams, so I would start there, if I were you.

**Comment by mattidupre** [comment]
@iDuuck:

``` javascript
.pipe(jade())
  .on('error', function(e) {
    gutil.log(gutil.colors.red(e.message));
    gutil.beep();
    this.emit('end');
  })
```

There's something funky going on with the error object Jade is handing out that prevents the stream from ending.
