### ISSUE TITLE
Using jade-filters with gulp-jade

### ISSUE THREAD

**Issue by ghost** [gulp-community/gulp-pug#91]
I'm trying to use [jade-filters](https://www.npmjs.com/package/jade-filter) with gulp-jade, but have no idea in how to get it working.

My current setup is:

``` coffee-script
jade = require 'jade'
gulpJade = require 'gulp-jade'
jadeFilter = require 'jade-filter'
config = require './config'

templates = gulp.src config.files.templates, base: config.folders.src
    .pipe gulpJade jadeFilter
        jade: jade
        locals: {}
        debug: no
        compileDebug: no
        basedir: config.folders.src
        pretty: yes
    .pipe gulp.dest config.folders.build
gulp.task 'templates', templates
```

Could someone help me with this?
It have to be a way...

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  Also, filter support was added and documented in 0.10 https://github.com/phated/gulp-jade/releases/tag/v0.10.0
