### ISSUE TITLE
shasum check failed

### ISSUE THREAD

**Issue by delch** [gulp-community/gulp-pug#95]
for npm install --save-dev gulp-jade i got:

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "gulp-jade"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for /var/folders/vr/y2cdyr7948b665vz7v23qppm0000gn/T/npm-8388-7678803c/registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
npm ERR! Expected: c8ce27de0acc76d896d2b1fad3df588d9e82f014
npm ERR! Actual:   904f60d6b58d5c5ffe2ef326248ba3075cffc298
npm ERR! From:     https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/delch/Sites/mollo/bin/npm-debug.log

**Comment by phated** [comment]
This has nothing to do with this package. Contact npm
