### ISSUE TITLE
Is it possible to use filters?

### ISSUE THREAD

**Issue by zhekaus** [gulp-community/gulp-pug#99]
I've tried to embed stylus styles into jade-file, but unsuccessful:

```
style
    :stylus
        html, body
            height 100%
```

I’ve got an error: Cannot find module 'stylus'

I've ried coffee with script tag - the same thing.

**Comment by phated** [comment]
Please read the docs.  It is discussed right in the [options](https://github.com/phated/gulp-jade#options) section.
